language: cpp
os: linux
dist: bionic

addons:
  apt:
    packages:
      - clang-format
      - clang-tidy
      - cppcheck
      - cmake
      - libglu1-mesa-dev
      - freeglut3-dev
      - mesa-common-dev
      - mesa-utils
      - glew-utils
      - libglew-dev
      - libglm-dev
      - libsoil-dev
      - libglfw3
      - libglfw3-dev
      - libassimp-dev
      - assimp-utils
      - libxmu-dev
      - libxi-dev


pull_request:
  branches:
    - main

script: 
  - clang-format for file in $(find . -iname '*.cpp' -or -iname '*.h' -and -not -iname 'doctest.h' ); do diff -u <(cat "$file") <(clang-format "$file") || exit 1; done
  - cmake . -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra" && cmake --build .
