language: cpp

dist: bionic

addons:
  apt:
    packages:
      - clang-format

on:
  pull_request:
    branches:
    - main

script: 
  - clang-format for file in $(find . -iname '*.cpp' -or -iname '*.h' -and -not -iname 'doctest.h' ); do diff -u <(cat "$file") <(clang-format "$file") || exit 1; done
