language: cpp
os: linux
dist: focal

addons:
  apt:
    packages:
      - assimp-utils
      - clang-format
      - clang-tidy
      - cmake
      - cppcheck
      - freeglut3
      - freeglut3-dev
      - glew-utils
      - libassimp-dev
      - libglew-dev
      - libglfw3
      - libglfw3-dev
      - libglm-dev
      - libglu1-mesa-dev
      - libsoil-dev
      - libxi-dev
      - libxmu-dev
      - mesa-common-dev
      - mesa-utils
      - xorg-dev

pull_request:
  branches:
    - main

notifications:
  email: false

jobs:
  include:
    - name: clang-format
      script: clang-format for file in $(find . -iname '*.cpp' -or -iname '*.h' -and -not -iname 'doctest.h' ); do diff -u <(cat "$file") <(clang-format "$file") || exit 1; done
    - name: clang-tidy, cppcheck
      script: cmake . -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra" && cmake --build .
    - name: compile-run
      matrix:
        compiler:
          - command: g++-10
            flags:
          - command: clang++-10
            flags: -stdlib=libstdc++
          - command: clang++-10
            flags: -stdlib=libc++
          sanitize:
            - flags: -fsanitize=undefined
              run-prefix: valgrind --quiet --leak-check=full --error-exitcode=123
            - flags: -fsanitize=undefined -fsanitize=address
              run-prefix:
      steps:
        - script: cmake . -DCMAKE_CXX_COMPILER="${{matrix.compiler.command}}" -DCMAKE_CXX_FLAGS="${{matrix.compiler.flags}} ${{matrix.sanitize.flags}}" -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=. ${{matrix.compiler.cmake-flags}}
        - script: cmake --build .
